version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./logs/apache:/var/log/apache2   # Mapea los logs de Apache a una carpeta en tu proyecto
      - ./logs/php:/var/log/php          # Mapea los logs de PHP a una carpeta en tu proyecto

    environment:
      - DB_HOST=db
      - DB_DATABASE=paco_librery_db
      - DB_USERNAME=paco_user
      - DB_PASSWORD=paco_password

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: paco_librery_db
      POSTGRES_USER: paco_user
      POSTGRES_PASSWORD: paco1234
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
