version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html                 # Mapea el código fuente
      - ./logs/apache:/var/log/apache2       # Mapea los logs de Apache
      - ./logs/php:/var/log/php              # Mapea los logs de PHP
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=paco_librery_db
      - DB_USERNAME=paco_user
      - DB_PASSWORD=paco1234
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: paco_librery_db
      POSTGRES_USER: paco_user
      POSTGRES_PASSWORD: paco1234
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
